// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmw02d1Tpi7gXQ3zFzq-vp0EHqTcvrQo',
    appId: '1:231784616255:web:a5a4ff3cc706de59e6c38a',
    messagingSenderId: '231784616255',
    projectId: 'maskoff-65b73',
    authDomain: 'maskoff-65b73.firebaseapp.com',
    storageBucket: 'maskoff-65b73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5H-t1kn1LgmKFe09johaW0oXjdCEerbM',
    appId: '1:231784616255:android:40a7b3e7576e6515e6c38a',
    messagingSenderId: '231784616255',
    projectId: 'maskoff-65b73',
    storageBucket: 'maskoff-65b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeN483XyTtVQefWxYu8dt_yW4L4lJfclo',
    appId: '1:231784616255:ios:60b51858d29299c9e6c38a',
    messagingSenderId: '231784616255',
    projectId: 'maskoff-65b73',
    storageBucket: 'maskoff-65b73.firebasestorage.app',
    iosBundleId: 'com.example.maskOff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeN483XyTtVQefWxYu8dt_yW4L4lJfclo',
    appId: '1:231784616255:ios:60b51858d29299c9e6c38a',
    messagingSenderId: '231784616255',
    projectId: 'maskoff-65b73',
    storageBucket: 'maskoff-65b73.firebasestorage.app',
    iosBundleId: 'com.example.maskOff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHmw02d1Tpi7gXQ3zFzq-vp0EHqTcvrQo',
    appId: '1:231784616255:web:4bcf084475b96692e6c38a',
    messagingSenderId: '231784616255',
    projectId: 'maskoff-65b73',
    authDomain: 'maskoff-65b73.firebaseapp.com',
    storageBucket: 'maskoff-65b73.firebasestorage.app',
  );
}
