import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:mask_off/main.dart'; 
import 'firebase_options.dart'; // generated by flutterfire configure

Future<void> firebaseStart() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.useFirestoreEmulator('172.15.2.124', 8080);

  final snapshot = await FirebaseFirestore.instance.collection('notes').get();
  print('Number of notes: ${snapshot.docs.length}');
}

Future<void> seedFirestore() async {
  final notesRef = FirebaseFirestore.instance.collection('notes');
  final snapshot = await notesRef.get();

  if (snapshot.docs.isEmpty) {
    await notesRef.add({
      "text": "I feel like I'm drowning in responsibilities. Every time I finish one thing, three more appear.", 
      "emotion": 5, "timeAgo": "12 min ago", 
      "hearCount": 8, 
      "aloneCount": 12
    });
    
    print('Seeded Firestore with test users.');
  } else {
    print('Firestore already has data, skipping seed.');
  }
}

Future<List<Post>> getAllPosts() async {
   // Reference to your Firestore collection
  CollectionReference<Map<String, dynamic>> collectionRef =
      FirebaseFirestore.instance.collection('notes');

  // Fetch all documents
  QuerySnapshot<Map<String, dynamic>> querySnapshot = await collectionRef.get();

  // Map documents to Post objects
  List<Post> allPosts = querySnapshot.docs.map((doc) {
    final data = doc.data();

    return Post(
      text: data['text'] ?? '',
      emotion: emotions[data['emotion'] ?? emotions[0]],
      timeAgo: data['timeAgo'] ?? '',
      hearCount: data['hearCount'] ?? 0,
      aloneCount: data['aloneCount'] ?? 0,
      isPinned: data['isPinned'] ?? false,
    );
  }).toList();

  print('Fetched ${allPosts.length} notes from Firestore.');
  return allPosts;
}